name: np_weather
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geocoding: ^2.0.5
  geolocator: ^8.2.0
  get: ^4.6.0
  google_fonts: ^3.0.1
  http: ^0.13.0
  iconsax: ^0.0.8
  intl: ^0.18.0
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/weather/01d.png
    - assets/weather/01n.png
    - assets/weather/02d.png
    - assets/weather/02n.png
    - assets/weather/03d.png
    - assets/weather/03n.png
    - assets/weather/04d.png
    - assets/weather/04n.png
    - assets/weather/09d.png
    - assets/weather/09n.png
    - assets/weather/10d.png
    - assets/weather/10n.png
    - assets/weather/11d.png
    - assets/weather/11n.png
    - assets/weather/13d.png
    - assets/weather/13n.png
    - assets/weather/50d.png
    - assets/weather/50n.png

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/font/NotoSans/NotoSans-Black.ttf
        - asset: assets/font/NotoSans/NotoSans-BlackItalic.ttf
        - asset: assets/font/NotoSans/NotoSans-Bold.ttf
        - asset: assets/font/NotoSans/NotoSans-BoldItalic.ttf
        - asset: assets/font/NotoSans/NotoSans-ExtraBold.ttf
        - asset: assets/font/NotoSans/NotoSans-ExtraBoldItalic.ttf
        - asset: assets/font/NotoSans/NotoSans-ExtraLight.ttf
        - asset: assets/font/NotoSans/NotoSans-ExtraLightItalic.ttf
        - asset: assets/font/NotoSans/NotoSans-Italic.ttf
        - asset: assets/font/NotoSans/NotoSans-Light.ttf
        - asset: assets/font/NotoSans/NotoSans-LightItalic.ttf
        - asset: assets/font/NotoSans/NotoSans-Medium.ttf
        - asset: assets/font/NotoSans/NotoSans-MediumItalic.ttf
        - asset: assets/font/NotoSans/NotoSans-Regular.ttf
        - asset: assets/font/NotoSans/NotoSans-SemiBold.ttf
        - asset: assets/font/NotoSans/NotoSans-SemiBoldItalic.ttf
        - asset: assets/font/NotoSans/NotoSans-Thin.ttf
        - asset: assets/font/NotoSans/NotoSans-ThinItalic.ttf
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
